export const REVERB_TOGGLE = 'REVERB_TOGGLE'
export const REVERB_REVERSE_TOGGLE = 'REVERB_REVERSE_TOGGLE'
export const REVERB_SET_LENGTH = 'REVERB_SET_LENGTH'
export const REVERB_SET_DECAY = 'REVERB_SET_DECAY'